### ISSUE TITLE
AttributeError: 'CacheControl' object has no attribute 'update_db'

### ISSUE THREAD

**Issue by SajidZakaria** [ParsaAlizadeh/TLE#20]
The following happens when I run the bot:
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/sajid/miniconda3/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/sajid/Projects/TLE BCS/tle/cogs/cache_control.py", line 31, in on_ready
    self.update_db.start()
AttributeError: 'CacheControl' object has no attribute 'update_db'
```

I've looked up but couldn't find any task named update_db(). Please look into it.

**Comment by ParsaAlizadeh** [comment]
I deleted that task in #19, and I forgot to remove this. I'll fix it right now.
